### ISSUE TITLE
Rstudio server?

### ISSUE THREAD

**Issue by ignacio82** [dashaub/ARM-RStudio#1]
It is possible to install [rstudio server](http://www.rstudio.com/products/rstudio/download-server/) on a raspberry pi using your script?

**Comment by henry-p** [comment]
Also interested!

**Comment by dashaub** [comment]
I don't have a Pi, but it is on my buy list. When I get one I'll try it out.

**Comment by jrowen** [comment]
@dashaub thanks a lot for putting this together.  FWIW, I was able to make a few changes and successfully build rstudio server on my ARM chromebook.  You can find the script at [jrowen/ARM-rstudio-server](https://github.com/jrowen/ARM-rstudio-server).

**Comment by dashaub** [comment]
Thanks for the good work @jrowen . I'm adding a link to the readme and closing the issue.
