### ISSUE TITLE
ERROR : /usr/local/bin/sift: line 7: syntax error near unexpected token `newline' /usr/local/bin/sift: line 7: `<!DOCTYPE html>'

### ISSUE THREAD

**Issue by ShahJainam24** [dashaub/ARM-RStudio#15]
i am trying to install sift on AWS EC2 ssh and as soon as i type sift install the following error displays:-

[ec2-user@ip-172-31-39-61 ~]$ sift install
/usr/local/bin/sift: line 7: syntax error near unexpected token newline' /usr/local/bin/sift: line 7: '
[ec2-user@ip-172-31-39-61 ~]$

Please help me resolve this issue

thank you in advance

**Comment by dashaub** [comment]
What is `sift` and why are you running it?

Also I'm guessing your EC2 instance is not ARM hardware. If it is just regular x86-64, there is no reason to use this project--just follow the regular install instructions from the RStudio website.
