### ISSUE TITLE
don't work

### ISSUE THREAD

**Issue by ailanshi** [dashaub/ARM-RStudio#3]
hi,

I followed your usage procedure, and finally there is a folder about rstudio in my computer, but I can't run rstudio, also I can't find it. so i wanna know how I can know I download it successfully and how can I run it? Thanks.

**Comment by dashaub** [comment]
@ailanshi What is the output/error you're getting?

**Comment by dashaub** [comment]
@ailanshi 

Should be working now. Please reopen the issue if not.
