### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by edgarobles97** [dashaub/ARM-RStudio#4]
I tried installing the .sh file but when it comes to compiling I get this:  Unable to find a javac compiler

**Comment by dashaub** [comment]
You need a java compiler. Which distro version are you using? Try something like `sudo apt-get install openjdk-8-jdk`.

**Comment by edgarobles97** [comment]
Thanks, the program installed successfully but now I get this every time I open RStudio: 

``Error in tools:::httpdPort <= 0L : 
  comparison (4) is possible only for atomic and list types``
Do I need to upgrade? And if that's the case, how do I do it?

PD: I'm using an Acer R13 Chromebook

**Comment by dashaub** [comment]
Yes, it looks like I need need to update the RStudio version number in the script. Could you give me some more information about your setup so I can fix this for everyone? Specifically could you run `lsb_release -a` and tell me that output.

**Comment by edgarobles97** [comment]
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```

**Comment by dashaub** [comment]
@edgarobles97 Looks like the RStudio build steps have changed quite a bit in the newer versions, so I'll need to update the script: there will need to be a separate version for Ubuntu 14.04 and 16.04. I have a lot on my plate right now and may not be able to make it to this for the next week or two.

**Comment by dashaub** [comment]
@edgarobles97 

Should be working now. Please reopen the issue if not.
