### ISSUE TITLE
Error (armhf chroot)

### ISSUE THREAD

**Issue by tlgoa** [dashaub/ARM-RStudio#7]
.........
- E: unable to locate package libgstreamer 0.10-0
- E:  couldn't find any package by glob 'libgstreamer 0.10-0'
- E:  couldn't find any package by regex 'libgstreamer 0.10-0'
.. help please

**Comment by dashaub** [comment]
@tlgoa  Which Ubuntu release is this on?

**Comment by tlgoa** [comment]
Bionic

**Comment by dashaub** [comment]
I'm working on updating the build to work on xenial, but I don't have access to a bionic machine. Hopefully this will work on bionic too.

**Comment by dashaub** [comment]
@tlgoa I'm getting the same error on xenial too when I follow the RStudio build instructions directly. This will need some work to refactor.

**Comment by dashaub** [comment]
@tlgoa 

Should be working now. Please reopen the issue if not.
