### ISSUE TITLE
line 7: syntax error near unexpected token `newline' <!DOCTYPE html>

### ISSUE THREAD

**Issue by hideoshiraishi** [dashaub/ARM-RStudio#8]
I am trying to install RStudio to my Galaxy tab s4 (ARM 64bit) via `Linux on dex` but failed.

My system environment is:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"

R.version
platform aarch64-unknown-linux-gnu
arch aarch64
os linux-gnu
version R version 3.2.3
(it cannot be updated to 3.4)

`ARM-RStudio.sh` is placed at `home` directory and ran following codes in the terminal:

sudo chmod a+x ARM-RStudio.sh
sudo ./ARM-RStudio.sh.

However, it returns the error with the following messages:

ARM-RStudio.sh: line 7: syntax error near unexpected token `newline`
ARM-RStudio.sh: line 7: `<!DOCTYPE html>`

I tired to apply some suggestions [here](https://askubuntu.com/questions/603809/syntax-error-near-unexpected-token-newline-doctype-html-while-installing-zpan), [here](https://askubuntu.com/questions/430231/how-to-install-zpanel-10-1-1-for-ubuntu-server-12-04-lts) and [here](https://support.rstudio.com/hc/en-us/community/posts/200656557-Building-RStudio-on-Ubuntu-Linux-on-ARM), however nothing solved.

I have a few years experience of using R but I am quite new to use Linux/Ubuntu.
It is highly appreciated if you have any suggestions to solve this issue.

**Comment by dashaub** [comment]
There should not be html in `ARM-RStudio.sh`. How did you download the file? My guess is you tried to right-click "save link as" download and it grabbed the html page. If you want just the `.sh` file, you'd need to download the [raw](https://raw.githubusercontent.com/dashaub/ARM-RStudio/master/ARM-RStudio.sh) file.

**Comment by hideoshiraishi** [comment]
Thank you, it run appropriately using the raw file that you kindly specified.
However, the program stopped to run when it suns `sudo apt-get install -y r-base r-base-dev wget openjdk-8-jdk checkinstall` and returns following code.
 
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 r-base : Depends: r-base-core (>= 3.4.4-1xenial0) but 3.2.3-4 is to be installed
          Depends: r-recommended (= 3.4.4-1xenial0) but 3.2.3-4 is to be installed
 r-base-dev : Depends: r-base-core (>= 3.4.4-1xenial0) but 3.2.3-4 is to be installed
E: Unable to correct problems, you have held broken packages.
```
The remaining parts of the codes seem to run but RStudio is not appeared.
I worry if my environment accepts R3.4 as the official web site shows the version 3.2.
https://launchpad.net/ubuntu/xenial/arm64/r-base
(However I do not know if 3.4 is required to install RStudio)

Hope if you have any solution.

**Comment by TymekDev** [comment]
@hideo-s regarding the R version, you could try building R from source. I have done so on my ARM chromebook to get the 3.5.1 version, however it was not for the RStudio purposes.

Dependencies I needed:
```
sudo apt-get install fort77 xorg-dev libblas-dev gobjc++ curl libcurl4-openssl-dev pandoc
```
Downloading and unpacking:
```
curl -O https://cran.r-project.org/src/base/R-3/R-3.5.1.tar.gz
tar xfz R-3.5.1.tar.gz
```
Configuration and installation:
```
cd R-3.5.1
./configure
make
sudo make install
```

This will install the R into your `/usr/bin` and it'll be available globally. Additionally, the R shared lib might be needed (sorry, I cannot really tell what for or when it is needed -- I used it for `rpy2` in Python). To include the lib, simply run the `./configure --enable-R-shlib` instead of just the `./configure`.

I hope it will be helpful in some way.

**Comment by hideoshiraishi** [comment]
It is really appreciated your support.
After running your codes, around 2,000 files are unfolded in `./usr/bin`.
However, I am still facing two issues:

1. How to run R 3.5.1 from command line?
It is really basic issue. However, if I put `R`, version 3.2.3 still appears in the terminal.

2. Installing RStudio
When I run `ARM-RStudio.sh`, it still stops at the same way as mentioned above.

It is sorry to ask such basic issue but I am still struggling with this issue.

**Comment by dashaub** [comment]
@hideo-s 

1. Installing from source will probably not add R to your `PATH`. You can run it by entering into the directory where `make` was configured to install it.

2. I'm afraid the install script isn't working right now. I'm trying to get it working again, but I have limited access to appropriate hardware. Also when I get this working again ti would probably be with an old version of RStudio.

**Comment by hideoshiraishi** [comment]
Thank you very much, I could run R 3.5.2 by specifying the program in the directory:

$ cd usr/local/bin bash R
$ bash R

On the other hand, RStudio still seems not to be installed properly.

1. Skipping installation of r
As installation of r makes an error, I skipped `r-base rbase-dev` from the following script.
`sudo apt-get install -y r-base r-base-dev wget openjdk-8-jdk checkinstall`
Then I could go to the next step.

2. Installation check failed
After running entire codes, the system stops due to memory usage which exceeds 4GB memory of my system during running `sudo checkinstall --pkgname rstudio --pkgversion "${PKG_VERS}" -y` or give following output which indicates that installation is not done correctly.

```
checkinstall 1.6.2, Copyright 2009 Felipe Eduardo Sanchez Diaz Duran
           This software is released under the GNU GPL.

The package documentation directory ./doc-pak does not exist. 
Should I create a default set of package docs?  [y]: y

Preparing package documentation...OK
*** No known documentation files were found. The new package 
*** won't include a documentation directory.

*****************************************
**** Debian package creation selected ***
*****************************************

This package will be built according to these values: 

0 -  Maintainer: [ root@localhost ]
1 -  Summary: [ Package created with checkinstall 1.6.2 ]
2 -  Name:    [ rstudio ]
3 -  Version: [ 20190119 ]
4 -  Release: [ 1 ]
5 -  License: [ GPL ]
6 -  Group:   [ checkinstall ]
7 -  Architecture: [ arm64 ]
8 -  Source location: [ build ]
9 -  Alternate source location: [  ]
10 - Requires: [  ]
11 - Provides: [ rstudio ]
12 - Conflicts: [  ]
13 - Replaces: [  ]

Enter a number to change any of them or press ENTER to continue: 

Installing with make install...

========================= Installation results ===========================
make: *** No rule to make target 'install'.  Stop.

****  Installation failed. Aborting package creation.
Restoring overwritten files from backup...OK
Cleaning up...OK
Bye.
```

`cmake` is done under `dextop@localhost:/tmp/rstudio-v1.1.447/build`.

I suppose following script installs RStudio on desktop, however it does not appear.
`sudo cmake .. -DRSTUDIO_TARGET=Desktop -DCMAKE_BUILD_TYPE=Release
` seems to create the program on desktop, right?

Ths is the output that I obtained after running `cmake`.

```
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- LSB release: ubuntu
-- Boost version: 1.63.0
-- Using RStudio-provided Boost 1.63.0
-- Performing Test HAVE_SCANDIR_POSIX
-- Performing Test HAVE_SCANDIR_POSIX - Success
-- Looking for SA_NOCLDWAIT
-- Looking for SA_NOCLDWAIT - found
-- Looking for SO_PEERCRED
-- Looking for SO_PEERCRED - found
-- Looking for inotify_init1
-- Looking for inotify_init1 - found
-- Looking for getpeereid
-- Looking for getpeereid - not found
-- Looking for setresuid
-- Looking for setresuid - found
-- Found LibR: /usr/local/lib/R  
-- Found R: /usr/local/lib/R
-- Performing Test LIBR_MINIMUM_VERSION
-- Performing Test LIBR_MINIMUM_VERSION - Success
-- Configuring done
CMake Warning (dev) in src/cpp/desktop/CMakeLists.txt:
  Policy CMP0043 is not set: Ignore COMPILE_DEFINITIONS_<Config> properties.
  Run "cmake --help-policy CMP0043" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in src/cpp/desktop/CMakeLists.txt:
  Policy CMP0043 is not set: Ignore COMPILE_DEFINITIONS_<Config> properties.
  Run "cmake --help-policy CMP0043" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /tmp/rstudio-v1.1.447/build
```

**Comment by hideoshiraishi** [comment]
Let me make short report of the progress.

As for an error `Policy CMP0043 is not set: Ignore COMPILE_DEFINITIONS_<Config> properties.`, I modified `CMakeLists.txt` in `src/cpp/desktop/` from `cmake_policy(SET CMP0043 OLD)` to `cmake_policy(SET CMP0020 OLD)`, then installation seems to be done as `cmake_policy(SET CMP0020 OLD)` resulted in the following codes:

```
dextop@localhost:/tmp/rstudio-v1.1.447/build$ sudo cmake .. -DRSTUDIO_TARGET=Desktop -DCMAKE_BUILD_TYPE=Release
-- Boost version: 1.63.0
-- Using RStudio-provided Boost 1.63.0
-- Found R: /usr/local/lib/R
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/rstudio-v1.1.447/build
```
However, during running `sudo checkinstall --pkgname rstudio --pkgversion "${PKG_VERS}" -y
`, my system stop to work due to memory shortage.

**Comment by dashaub** [comment]
@hideo-s 

Should be working now. Please reopen the issue if not.

**Comment by ShahJainam24** [comment]
i am trying to install sift on AWS EC2 ssh and as soon as i type sift install the following error displays:-

[ec2-user@ip-172-31-39-61 ~]$ sift install
/usr/local/bin/sift: line 7: syntax error near unexpected token `newline'
/usr/local/bin/sift: line 7: `<!DOCTYPE html>'
[ec2-user@ip-172-31-39-61 ~]$

Please help me resolve this issue

thank you in advance
